name: CI - Frontend & Backend

on:
  push:
  pull_request:

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies (frontend)
        working-directory: frontend
        run: npm install

      - name: Run frontend tests
        working-directory: frontend
        run: npm test

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-logs
          path: frontend/package.json

  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies (backend)
        working-directory: backend
        run: npm install

      - name: Run backend tests
        working-directory: backend
        run: npm test

      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-logs
          path: backend/package.json
  notify:
    runs-on: ubuntu-latest
    needs: [frontend, backend]
    steps:
      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: |
            ✅ CI/CD pipeline finished.
            Frontend & Backend tested successfully.
            Status: ${{ job.status }}

